### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [stshrewsburyDev/PySliders#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pysliders -w /tmp/ext pysliders==0.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pysliders==0.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/08a/bb5f5eaeff1fd/PySliders-0.1.tar.gz (5.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-far8_4ws/pysliders/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-far8_4ws/pysliders/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-far8_4ws/pysliders/pip-egg-info
         cwd: /tmp/pip-wheel-far8_4ws/pysliders/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-far8_4ws/pysliders/setup.py", line 3, in <module>
        with open('README-PyPi.txt', 'r') as README_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'README-PyPi.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by SkylaDev** [comment]
wow didnt know people actually used this module.
I have made a 0.1.1 release which I have tested and it seems that this error is resolved. Thanks for reporting it.
Any other problems or concerns dont hesitate to make a new report about it.
